#!/bin/bash

function install_random() {
  pip install --upgrade pip
  sudo apt install -y exfat-utils exfat-fuse
  # Not sure I need to do this....
  sudo apt remove -y --purge alsa-base alsa-utils pulseaudio indicator-sound
  sudo apt install -y alsa-base alsa-utils pulseaudio indicator-sound
  sudo apt install -y audacity
  sudo apt install -y openscad
  sudo apt install -y youtube-dl
  sudo alsa force-reload

  # Install Virtualbox & VLC & ImageMagick
  sudo apt install -y virtualbox imagemagick vlc

  # Install powerline
  pip install powerline-shell

  # Install nonsense
  sudo apt install -y ruby
  sudo gem install lolcat
  sudo apt install -y figlet cowsay fortune
  figlet noice! | lolcat

  # make nautilus not stupid
  sudo apt remove -y nautilus-share
  sudo apt install -y nautilus-share
  mkdir -p /var/lib/samba/usershares

  # install OBS
  sudo apt install -y ffmpeg 
  sudo add-apt-repository ppa:obsproject/obs-studio
  sudo apt update
  sudo apt install -y obs-studio # TODO - I think this makes your push enter....

  # Firewall
  sudo ufw enable
  sudo ufw status
  
}

install_random